blank_issues_enabled: false
contact_links:
  - name: Support Request
    url: https://wordpress.org/support/plugin/fast-smooth-scroll/
    about: Ask for help in the Fast Smooth Scroll support forum.
